name: Deploy
on:
  push:
    branches:
      - main
#jobs:
#  build:
#    name: Run Web App
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out repository
#        uses: actions/checkout@v3
#        with:
#          repository: praveen6370/actions
#          ref: main
#          token: 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
#          path: ./.github/workflows/
#      - name: Run my action
#        uses: ./.github/workflows/blank.yml
#
#    steps:
#      - name: Build Web App
#        run: |
#          echo "Build Web App"
##          sleep 11s
#      - uses: actions/checkout@v3
#        with:
##          owner: praveen6370
##          repo:  actions
##          github_token: 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
##          workflow_file_name: blank.yml
#          repository: praveen6370/actions
##          token: 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
#name: Repository Dispatch
#on:
#  repository_dispatch:
#    types: [tests]
#jobs:
#  tests:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Dump the client payload context
#        env:
#          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
#        run: echo "$PAYLOAD_CONTEXT"
#
#      - uses: actions/checkout@v3
#        if: github.event.client_payload.ref != ''
#        with:
#          ref: ${{ github.event.client_payload.ref }}
#
#      - run: echo ${{ github.event.client_payload.sha }}
jobs:
  call-workflow:
    uses: praveen6370/actions/.github/workflows/blank.yml@main
    with:
      username: praveen6370
      github_token: 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
