name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 11s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: praveen6370
          repo:  actions
          github_token: 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
          workflow_file_name: blank.yml
